### ISSUE TITLE
Issue with "using namespace cv"

### ISSUE THREAD

**Issue by mustwillza** [manashmndl/SerialPort#1]
I would report this conflict after i using OpenCV Library with this library.
The conflict result when declare "using namespace cv". In my opinion it might have conflict on Window serial library.

**Comment by manashmandal** [comment]
Could you paste the error message here? Thanks!

**Comment by mustwillza** [comment]
![image](https://user-images.githubusercontent.com/7556484/31494717-5263b8a8-afa0-11e7-8a82-db521007c5c2.png)
Here is the error after i declare using namespace cv before include SerialPort Library

but after use cv:: instead all work fine

**Comment by manashmandal** [comment]
The conflict might be occurring due to `windows.h` file. I didn't actually use OpenCV with this library so can't tell. So using `cv::cvFunction` working right?
