### ISSUE TITLE
Pointer misuse

### ISSUE THREAD

**Issue by ben-j-c** [manashmndl/SerialPort#14]
https://github.com/manashmandal/SerialPort/blob/db06eadc392b657bddd5206a85dccc7514826e0e/src/SerialPort.cpp#L92
https://github.com/manashmandal/SerialPort/blob/db06eadc392b657bddd5206a85dccc7514826e0e/src/SerialPort.cpp#L94

Referencing the pointer here is incorrect. It just needs to be cast to a void pointer. The lines should be:
```
memset((void*) buffer, 0, buf_size);

if (ReadFile(this->handler, (void*) buffer, toRead, &bytesRead, NULL))
```

**Comment by space55** [comment]
This seemed to fix my lack of receiving data! It would be great if this could be pulled into the main repo, as I'm very grateful someone posted this, fixing my issue.

Thanks!

**Comment by manashmandal** [comment]
Thanks for feedback. Modified master branch with this update.
