### ISSUE TITLE
Windows receive wrong sentence

### ISSUE THREAD

**Issue by gonnavis** [manashmndl/SerialPort#2]
I run the exampleReceiveData on windows7, it first receive true sentence "Hello, world!", but afterwards the sentence has been cluttered for example "llo, wororld!", "ld!", "wororld!", "Hel", "wororld!", "lo, worrorld!".

**Comment by manashmandal** [comment]
Don't know what's the problem, clear the buffer then try again maybe? I don't have an arduino lying around to try. Sorry :(

**Comment by iJetColor** [comment]
I have a very similar issue. The first string I get back is intact, but all strings after that are partial or nonsensical. Also, the first string I send works perfectly, but strings I send after that do not appear to reach the Arduino intact. It also seems as though the library itself is sending unknown data to the Arduino that the Arduino then responds to. I'm having a hard time isolating exactly what data is being sent back and forth.

**Comment by iJetColor** [comment]
The issue appears to be caused by passing a number greater than the length of the data string to SerialPort::writeSerialPort(const char *buffer, unsigned int buf_size). buf_size ought to be the number of characters in *buffer.
