### ISSUE TITLE
How to know when port is disconnected after connection

### ISSUE THREAD

**Issue by TejaswiniiB** [manashmndl/SerialPort#3]
Hi, after successful connection, 
when port is disconnected, how would I know if it's disconnected?

Thanks !

**Comment by manashmandal** [comment]
That's what `isConnected` method for. 

`arduino->isConnected();` will return false if there is no connection.

**Comment by TejaswiniiB** [comment]
Yes, I know that isConnected variable is present in src code. But you are updating it to false only in destructor. So where are you setting it to false when arduino is disconnected from port ?

**Comment by manashmandal** [comment]
I didn't add it to the library interface, thanks for pointing it out. But you could try sending data couple of time if it replies false then your arduino must have been disconnected.

**Comment by TejaswiniiB** [comment]
Yes doing that only as of now. But in c++, is there any other way to know if its disconnected?

Thankyou.

**Comment by manashmandal** [comment]
Wrote this library a while ago, didn't work with embedded systems after that. Sorry I don't remember.

**Comment by TejaswiniiB** [comment]
Okay.

**Comment by julien-mustiere** [comment]
solved see my pull-request: https://github.com/manashmndl/SerialPort/pull/7

**Comment by manashmandal** [comment]
@julien-mustiere thank you!
